on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout
    - uses: actions/setup-node
    - run: npm i -g esbuild
    - run: esbuild --bundle little-planet.js > dist/little-planet.js

