name: Bundle & publish
on:
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          registry-url: "https://npm.pkg.github.com"

      - run: npm i -g esbuild

      - name: esbuild
        run: mkdir -p dist; esbuild --format=esm --bundle little-planet.js > dist/little-planet.js

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
