on: workflow_dispatch
name: Bundle & publish

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v4
      with:
        registry-url: 'https://npm.pkg.github.com'
    - run: npm i -g esbuild
    - run: esbuild --bundle little-planet.js > dist/little-planet.js

